name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean verify

        
 #Step 4: GitHub Actions CI/CD Setup
#✅ What This Will Do:
#Run mvn clean verify on every push/pull request

#Ensure build and tests pass before merging code 
#📁 .github/workflows/
 #   └── ci.yml
      